// <auto-generated />
namespace TiemVaiLucCode.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.2")]
    public sealed partial class ThemBangDonHangVaChiTiet : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ThemBangDonHangVaChiTiet));
        
        string IMigrationMetadata.Id
        {
            get { return "202608140436195_ThemBangDonHangVaChiTiet"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
